# PANDAS

In [14]:
import numpy as np 
import pandas as pd

In [2]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [3]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [4]:
df.to_csv('F20file1.csv')

In [5]:
df.to_csv('F20file2.csv',index=False)

In [6]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [7]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [8]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [9]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [10]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [11]:
z['name'][0]

'F-22'

In [12]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [16]:
#z.to_csv('F20file3.csv')

In [ ]:
ser=pd.Series(np.random.rand(10))
ser

0    0.622722
1    0.199052
2    0.256186
3    0.824833
4    0.174820
5    0.565593
6    0.974885
7    0.873063
8    0.668318
9    0.630536
dtype: float64

In [ ]:
type(ser)

pandas.Series

In [17]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.397314  0.395114  0.059438  0.890089  0.421118
1  0.297441  0.475851  0.969424  0.224565  0.209864
2  0.138517  0.118858  0.285406  0.858676  0.528066
3  0.354476  0.956019  0.392527  0.347017  0.466866
4  0.671708  0.069636  0.936762  0.167340  0.878884

In [18]:
type(newdf)

pandas.DataFrame

In [20]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.501776    0.505082    0.466923    0.495171    0.531809
std      0.280268    0.312803    0.282638    0.286338    0.305669
min      0.002231    0.002412    0.002967    0.010566    0.003013
25%      0.262915    0.209948    0.221242    0.254612    0.256360
50%      0.514602    0.524307    0.463532    0.483870    0.563363
75%      0.743004    0.780334    0.722333    0.737822    0.805070
max      0.999637    0.999675    0.996215    0.998312    0.999642

In [21]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
newd